version: '3.9'
services: 
  backend:
    image: backend
    build: .
    ports:
      - "3000:3000"
    restart: always
    environment:
      DB_HOST: db
    depends_on:
      - db
    networks:
      - backend
    
  db:
    image: mysql/mysql-server:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - backend

networks:
  backend:
    driver: bridge